name: national_sites_bulgaria
description: Project for the bulgarian national sites.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider: any
  flex_color_scheme: any
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  animated_theme_switcher: ^2.0.6
  lottie: ^1.2.2
  flutter_spinkit: ^5.1.0
  flutter_keyboard_visibility: any
  day_night_switcher: ^0.2.0+1
  curved_navigation_bar: ^1.0.3
  animations: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  flutter_switch: ^0.3.2
  json_serializable: ^6.1.0
  json_annotation: ^4.4.0
  cached_network_image: ^3.2.0
  flutter_blurhash: ^0.6.0
  url_launcher: ^6.1.0
  flutter_rating_bar: ^4.0.0
  timeago: ^3.2.2
  easy_debounce: ^2.0.2+1
  file_picker: ^4.4.0
  image_picker: ^0.8.4+9
  flutter_image_compress: ^1.1.0
  collection: any
  flutter_linkify: ^5.0.2

  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

